apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend-namespace
spec:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  ports:
    - port: 80
      targetPort: 5000  # Map to the backend application port
  selector:
    app: backend
