apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80          # Port exposed externally
      targetPort: 3000   # Port inside your pod (application port)
  selector:
    app: frontend
